apiVersion: apps/v1
kind: Deployment
metadata:
  name: repair
  labels:
    app: repair
spec:
  replicas: 1
  selector:
    matchLabels:
      app: repair
  template:
    metadata:
      labels:
        app: repair
    spec:
      containers:
        - name: repair
          image: username/repair:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5